(() => {
'use strict';
const state={allTools:[],filtered:[],listLimit:24,page:document.body.dataset.page,favorites:JSON.parse(localStorage.getItem('aiTools:favorites')||'[]'),theme:localStorage.getItem('aiTools:theme')||'light',creatorLookup:new Map()};
const $=(s,r=document)=>r.querySelector(s);
const escapeHtml=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const getLogoUrl=(l,s=96)=>{try{return `https://www.google.com/s2/favicons?domain=${new URL(l).hostname.replace(/^www\./,'')}&sz=${s}`;}catch{return ''}};
function applyTheme(t){state.theme=t==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',state.theme);localStorage.setItem('aiTools:theme',state.theme);const b=$('#themeToggle');if(b)b.textContent=state.theme==='dark'?'☀️':'🌙';}
function initUi(){applyTheme(state.theme);$('#themeToggle')?.addEventListener('click',()=>applyTheme(state.theme==='dark'?'light':'dark'));$('#year')&&($('#year').textContent=new Date().getFullYear());}
function creatorBadge(toolId){const picks=state.creatorLookup.get(Number(toolId));if(!picks?.length) return '';const txt=picks.length>1?`⭐ Picked by <strong>${escapeHtml(picks[0].name)}</strong> +${picks.length-1} more`:`⭐ Picked by <strong>${escapeHtml(picks[0].name)}</strong>`;return `<div class="creator-pick-badge">${txt}</div>`;}
function createCard(t){return `<article class="tool-card"><div class="tool-card-top"><img class="tool-logo" src="${escapeHtml(getLogoUrl(t.link))}" alt="${escapeHtml(t.title)} logo" onerror="this.src='./fallback.png'"><div class="tool-card-meta"><a class="badge badge-link" href="category.html?name=${encodeURIComponent(t.category)}">${escapeHtml(t.category)}</a></div></div><h3>${escapeHtml(t.title)}</h3><p class="description-2">${escapeHtml((t.description||'').replace(/\[[^\]]+\]\(([^)]+)\)/g,'$1'))}</p>${creatorBadge(t.id)}<div class="card-actions"><a class="btn btn-secondary" href="detailed.html?id=${t.id}">View Details</a></div></article>`}
async function initIndex(){const g=$('#trendingGrid');const tools=[...state.allTools].sort((a,b)=>new Date(b.$createdAt)-new Date(a.$createdAt));g.innerHTML=tools.slice(0,8).map(createCard).join('');const total=tools.length,cats=new Set(tools.map(t=>t.category)).size;animate($('#totalTools'),total);animate($('#totalCategories'),cats);const stats={};tools.forEach(t=>stats[t.category]=(stats[t.category]||0)+1);$('#categoryStats').innerHTML=Object.entries(stats).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<a class="category-pill category-link" href="category.html?name=${encodeURIComponent(c)}"><span>${escapeHtml(c)}</span><strong>${n}</strong></a>`).join('');const creators=await window.AppwriteLayer.fetchAllCreators();$('#creatorPreviewStrip')&&($('#creatorPreviewStrip').innerHTML=creators.sort((a,b)=>(b.featured?1:0)-(a.featured?1:0)).slice(0,4).map(c=>`<a class="creator-mini" href="creators.html?slug=${c.slug}"><img src="${c.avatar_url}" alt="${escapeHtml(c.name)}"><span>${escapeHtml(c.name)}</span><small>${(c.pick_ids||[]).length} picks</small></a>`).join(''));}
function animate(el,target){if(!el)return;const s=performance.now(),d=1200;const tick=(n)=>{const p=Math.min((n-s)/d,1);el.textContent=Math.floor(target*p).toLocaleString();if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
function initList(){const grid=$('#toolsGrid');grid.innerHTML='<div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div>';const search=$('#searchInput'),cat=$('#categoryFilter'),sort=$('#sortFilter');sort.value='id-desc';const cats=[...new Set(state.allTools.map(t=>t.category))].sort();cat.innerHTML+=[...cats].map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');const render=()=>{let data=[...state.allTools];if(search.value)data=data.filter(t=>t.title.toLowerCase().includes(search.value.toLowerCase()));if(cat.value!=='all')data=data.filter(t=>t.category===cat.value);if(sort.value==='id-desc')data.sort((a,b)=>new Date(b.$createdAt)-new Date(a.$createdAt));if(sort.value==='id-asc')data.sort((a,b)=>new Date(a.$createdAt)-new Date(b.$createdAt));if(sort.value==='title-asc')data.sort((a,b)=>a.title.localeCompare(b.title));if(sort.value==='title-desc')data.sort((a,b)=>b.title.localeCompare(a.title));state.filtered=data;grid.innerHTML=data.slice(0,state.listLimit).map(createCard).join('');$('#resultsCount').textContent=`${data.length} tools found`;};search.oninput=render;cat.onchange=render;sort.onchange=render;render();}
async function initDetailed(){const id=Number(new URLSearchParams(location.search).get('id'));const tool=await window.AppwriteLayer.fetchToolById(id);if(!tool){$('#notFound')?.classList.remove('hidden');return;}const ranks=await window.AppwriteLayer.fetchAllRanks();const rank=ranks.find(r=>Number(r.id)===id);const creators=state.creatorLookup.get(id)||[];localStorage.setItem('mz_recently_viewed',JSON.stringify([{id:tool.id,title:tool.title,category:tool.category},...(JSON.parse(localStorage.getItem('mz_recently_viewed')||'[]').filter(x=>x.id!==tool.id))].slice(0,8)));$('#toolDetails').innerHTML=`<div class="detail-head"><img class="tool-logo tool-logo-lg" src="${getLogoUrl(tool.link,128)}"><div><h1>${escapeHtml(tool.title)}</h1><a class="badge badge-link" href="category.html?name=${encodeURIComponent(tool.category)}">${escapeHtml(tool.category)}</a></div></div><p>${escapeHtml(tool.description||'')}</p>${rank?`<div class="detail-rank-card"><h3>📊 Rankings Score</h3><div class="rank-scores-row"><div class="rank-score-item"><span class="score-num">${rank.overall}</span><span class="score-lbl">Overall</span></div><div class="rank-score-item"><span class="score-num">${rank.reasoning}</span><span class="score-lbl">Reasoning</span></div><div class="rank-score-item"><span class="score-num">${rank.coding}</span><span class="score-lbl">Coding</span></div><div class="rank-score-item"><span class="score-num">${rank.vision}</span><span class="score-lbl">Vision</span></div><div class="rank-score-item"><span class="score-num">${parseInt(rank.context,10)}</span><span class="score-lbl">Context</span></div></div><a href="rankings.html" class="text-link">See full rankings →</a></div>`:''}${creators.length?`<div class="creator-endorsements"><h3>🎬 Creator Endorsed</h3>${creators.map(c=>`<a class="creator-chip" href="creators.html?slug=${c.slug}"><img src="${c.avatar_url}">${escapeHtml(c.name)}</a>`).join('')}</div>`:''}`}
(async function(){initUi();state.allTools=await window.AppwriteLayer.fetchAllTools();state.creatorLookup=await window.AppwriteLayer.getCreatorPickLookup();if(state.page==='index')await initIndex();if(state.page==='list')initList();if(state.page==='detailed')await initDetailed();})();
})();
